---
title: "Sharing Data 2020"
author: "Matt Wan"
date: "6.18.2020"
output: html_notebook
---

Set up 

```{r set up, include=FALSE}
library(rethinking)
library(readr)
library(ggplot2)
setwd("~/Documents/Google Drive/Reed/Learning & Adaptive Behavior Laboratory/Sharing Data - Matt")

Behav <- read_excel("Raw_data.xlsx")
Behav$Subject <- coerce_index(Behav$Rat)

rstan_options(auto_write = TRUE);
options(mc.cores = parallel::detectCores());
```

Model 

```{r}
library(rstan)
mcode <- "
data{
	int<lower=1> S;         // Number of sessions
	int<lower=1> C;         // Number of conditions
	int<lower=0> N[S];      // Number of choices per session
	int<lower=1> condID[S]; // Condition ID
	int<lower=0> F[S];      // Number of food choices (such that N[s]-F[s]=Social[s])
}
parameters{
	real intercept[C];
}
model{
	real mu[S];
	intercept ~ normal(0,1.5);
	for ( s in 1:S ) {
		mu[s] = intercept[condID[s]];
	}
	F ~ binomial_logit(N,mu);
}
"

mdata_1 <- (Behav$Condition!=5)&(Behav$Subject==s)
mdata_2 <- list(S=sum(mdata_1),C=length(unique(Behav$Condition[mdata_1])),N=Behav$Social[mdata_1]+Behav$Food[mdata_1],condID=Behav$Condition[mdata_1],F=Behav$Food[mdata_1])
mdata_2$condID[mdata_2$condID>5] <- mdata_2$condID[mdata_2$condID>5]-1
nsample <- 2000

fs.stan.mcmc <- stan(model_code = mcode, data = mdata_2, iter=nsample*2, warmup=nsample, chains=4, cores=1, control=list(adapt_delta=0.99,max_treedepth=15))

precis(fs.stan.mcmc, depth = 2)
smry <- summary(fs.stan.mcmc)
print(smry$summary, digits=3)
```

Posterior estimation


```{r}
post_1 <- extract.samples(fs.stan.mcmc)
precis(post_1, depth = 2)
post_2 <- inv_logit(post_1$intercept)
precis(post_2)

plotdata <- data.frame(
  name = c( rep("Cond 1",8000), rep("Cond 2",8000), rep("Cond 3",8000), rep("Cond 4",8000), rep("Cond 6",8000), rep("Cond 7",8000) ),
  intercept = c( post_1$intercept[1],post_1$intercept[2],post_1$intercept[3],post_1$intercept[4],post_1$intercept[5],post_1$intercept[6] )
)
p <- ggplot(plotdata, aes(x=name, y=intercept, fill=name)) +
  geom_violin()
print(p)

plotdata <- data.frame(
  name = c( rep("Cond 1",8000), rep("Cond 2",8000), rep("Cond 3",8000), rep("Cond 4",8000), rep("Cond 6",8000), rep("Cond 7",8000) ),
  proportion = c( post_2[,1],post_2[,2],post_2[,3],post_2[,4],post_2[,5],post_2[,6] )
)
p <- ggplot(plotdata, aes(x=name, y=proportion, fill=name)) +
  geom_violin()
print(p)
```

