---
title: "R - Empathy"
output: html_notebook
---


Summary Data (This part can be ignored, it is just for checking)
```{r}

ind_Cond1 <- Raw_data$Condition==1
ind_Cond2 <- Raw_data$Condition==2
ind_Cond3 <- Raw_data$Condition==3
ind_Cond4 <- Raw_data$Condition==4
ind_Cond5 <- Raw_data$Condition==5
ind_Cond6 <- Raw_data$Condition==6
ind_Cond7 <- Raw_data$Condition==7
rat_4 <- Raw_data$Rat==4
rat_6 <- Raw_data$Rat==6
rat_8 <- Raw_data$Rat==8

Condition <- c(1,2,3,4,5,6,7)

## Rat 4
# Relative social response 
mean_rel_soc_4_c1 <- mean(Raw_data$`Rel. Soc`[ind_Cond1&rat_4])
mean_rel_soc_4_c2 <- mean(Raw_data$`Rel. Soc`[ind_Cond2&rat_4])
mean_rel_soc_4_c3 <- mean(Raw_data$`Rel. Soc`[ind_Cond3&rat_4])
mean_rel_soc_4_c4 <- mean(Raw_data$`Rel. Soc`[ind_Cond4&rat_4])
mean_rel_soc_4_c5 <- mean(Raw_data$`Rel. Soc`[ind_Cond5&rat_4])
mean_rel_soc_4_c6 <- mean(Raw_data$`Rel. Soc`[ind_Cond6&rat_4])
mean_rel_soc_4_c7 <- mean(Raw_data$`Rel. Soc`[ind_Cond7&rat_4])
# Relative food response
mean_rel_food_4_c1 <- mean(Raw_data$`Rel. Food`[ind_Cond1&rat_4])
mean_rel_food_4_c2 <- mean(Raw_data$`Rel. Food`[ind_Cond2&rat_4])
mean_rel_food_4_c3 <- mean(Raw_data$`Rel. Food`[ind_Cond3&rat_4])
mean_rel_food_4_c4 <- mean(Raw_data$`Rel. Food`[ind_Cond4&rat_4])
mean_rel_food_4_c5 <- mean(Raw_data$`Rel. Food`[ind_Cond5&rat_4])
mean_rel_food_4_c6 <- mean(Raw_data$`Rel. Food`[ind_Cond6&rat_4])
mean_rel_food_4_c7 <- mean(Raw_data$`Rel. Food`[ind_Cond7&rat_4])

## Rat 6
# Relative social response 
mean_rel_soc_6_c1 <- mean(Raw_data$`Rel. Soc`[ind_Cond1&rat_6])
mean_rel_soc_6_c2 <- mean(Raw_data$`Rel. Soc`[ind_Cond2&rat_6])
mean_rel_soc_6_c3 <- mean(Raw_data$`Rel. Soc`[ind_Cond3&rat_6])
mean_rel_soc_6_c4 <- mean(Raw_data$`Rel. Soc`[ind_Cond4&rat_6])
mean_rel_soc_6_c5 <- mean(Raw_data$`Rel. Soc`[ind_Cond5&rat_6])
mean_rel_soc_6_c6 <- mean(Raw_data$`Rel. Soc`[ind_Cond6&rat_6])
mean_rel_soc_6_c7 <- mean(Raw_data$`Rel. Soc`[ind_Cond7&rat_6])
# Relative food response
mean_rel_food_6_c1 <- mean(Raw_data$`Rel. Food`[ind_Cond1&rat_6])
mean_rel_food_6_c2 <- mean(Raw_data$`Rel. Food`[ind_Cond2&rat_6])
mean_rel_food_6_c3 <- mean(Raw_data$`Rel. Food`[ind_Cond3&rat_6])
mean_rel_food_6_c4 <- mean(Raw_data$`Rel. Food`[ind_Cond4&rat_6])
mean_rel_food_6_c5 <- mean(Raw_data$`Rel. Food`[ind_Cond5&rat_6])
mean_rel_food_6_c6 <- mean(Raw_data$`Rel. Food`[ind_Cond6&rat_6])
mean_rel_food_6_c7 <- mean(Raw_data$`Rel. Food`[ind_Cond7&rat_6])

## Rat 8
# Relative social response 
mean_rel_soc_8_c1 <- mean(Raw_data$`Rel. Soc`[ind_Cond1&rat_8])
mean_rel_soc_8_c2 <- mean(Raw_data$`Rel. Soc`[ind_Cond2&rat_8])
mean_rel_soc_8_c3 <- mean(Raw_data$`Rel. Soc`[ind_Cond3&rat_8])
mean_rel_soc_8_c4 <- mean(Raw_data$`Rel. Soc`[ind_Cond4&rat_8])
mean_rel_soc_8_c5 <- mean(Raw_data$`Rel. Soc`[ind_Cond5&rat_8])
mean_rel_soc_8_c6 <- mean(Raw_data$`Rel. Soc`[ind_Cond6&rat_8])
mean_rel_soc_8_c7 <- mean(Raw_data$`Rel. Soc`[ind_Cond7&rat_8])
# Relative food response
mean_rel_food_8_c1 <- mean(Raw_data$`Rel. Food`[ind_Cond1&rat_8])
mean_rel_food_8_c2 <- mean(Raw_data$`Rel. Food`[ind_Cond2&rat_8])
mean_rel_food_8_c3 <- mean(Raw_data$`Rel. Food`[ind_Cond3&rat_8])
mean_rel_food_8_c4 <- mean(Raw_data$`Rel. Food`[ind_Cond4&rat_8])
mean_rel_food_8_c5 <- mean(Raw_data$`Rel. Food`[ind_Cond5&rat_8])
mean_rel_food_8_c6 <- mean(Raw_data$`Rel. Food`[ind_Cond6&rat_8])
mean_rel_food_8_c7 <- mean(Raw_data$`Rel. Food`[ind_Cond7&rat_8])

## All Rat 
# Relative social response 
mean_rel_soc_c1 <- mean(Raw_data$`Rel. Soc`[ind_Cond1])
mean_rel_soc_c2 <- mean(Raw_data$`Rel. Soc`[ind_Cond2])
mean_rel_soc_c3 <- mean(Raw_data$`Rel. Soc`[ind_Cond3])
mean_rel_soc_c4 <- mean(Raw_data$`Rel. Soc`[ind_Cond4])
mean_rel_soc_c5 <- mean(Raw_data$`Rel. Soc`[ind_Cond5])
mean_rel_soc_c6 <- mean(Raw_data$`Rel. Soc`[ind_Cond6])
mean_rel_soc_c7 <- mean(Raw_data$`Rel. Soc`[ind_Cond7])
# Relative food response
mean_rel_food_c1 <- mean(Raw_data$`Rel. Food`[ind_Cond1])
mean_rel_food_c2 <- mean(Raw_data$`Rel. Food`[ind_Cond2])
mean_rel_food_c3 <- mean(Raw_data$`Rel. Food`[ind_Cond3])
mean_rel_food_c4 <- mean(Raw_data$`Rel. Food`[ind_Cond4])
mean_rel_food_c5 <- mean(Raw_data$`Rel. Food`[ind_Cond5])
mean_rel_food_c6 <- mean(Raw_data$`Rel. Food`[ind_Cond6])
mean_rel_food_c7 <- mean(Raw_data$`Rel. Food`[ind_Cond7])

```

Fig 1. Relative preference across 6 choice conditions
```{r}

Raw_data_withsoc <- subset(Raw_data, `Social ` !=-1)
ind_Cond1 <- Raw_data_withsoc$Condition==1
ind_Cond2 <- Raw_data_withsoc$Condition==2
ind_Cond3 <- Raw_data_withsoc$Condition==3
ind_Cond4 <- Raw_data_withsoc$Condition==4
ind_Cond6 <- Raw_data_withsoc$Condition==6
ind_Cond7 <- Raw_data_withsoc$Condition==7
rat_4 <- Raw_data_withsoc$Rat==4
rat_6 <- Raw_data_withsoc$Rat==6
rat_8 <- Raw_data_withsoc$Rat==8

# Rat 4
boxplot(Raw_data_withsoc$`Rel. Soc`[ind_Cond1&rat_4], 
        Raw_data_withsoc$`Rel. Food`[ind_Cond1&rat_4], 
        Raw_data_withsoc$`Rel. Soc`[ind_Cond2&rat_4],
        Raw_data_withsoc$`Rel. Food`[ind_Cond2&rat_4], 
        Raw_data_withsoc$`Rel. Soc`[ind_Cond3&rat_4],
        Raw_data_withsoc$`Rel. Food`[ind_Cond3&rat_4],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond4&rat_4],
        Raw_data_withsoc$`Rel. Food`[ind_Cond4&rat_4],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond6&rat_4],
        Raw_data_withsoc$`Rel. Food`[ind_Cond6&rat_4],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond7&rat_4],
        Raw_data_withsoc$`Rel. Food`[ind_Cond7&rat_4],
        main = "Rat 4: Relative preference across 6 choice conditions",
        at = c(1,2, 4,5, 7,8, 10,11, 13,14, 16,17),
        names = c("Rel. Soc", "Rel. Food", "Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food")
        )

# Rat 6
boxplot(Raw_data_withsoc$`Rel. Soc`[ind_Cond1&rat_6], 
        Raw_data_withsoc$`Rel. Food`[ind_Cond1&rat_6], 
        Raw_data_withsoc$`Rel. Soc`[ind_Cond2&rat_6],
        Raw_data_withsoc$`Rel. Food`[ind_Cond2&rat_6], 
        Raw_data_withsoc$`Rel. Soc`[ind_Cond3&rat_6],
        Raw_data_withsoc$`Rel. Food`[ind_Cond3&rat_6],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond4&rat_6],
        Raw_data_withsoc$`Rel. Food`[ind_Cond4&rat_6],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond6&rat_6],
        Raw_data_withsoc$`Rel. Food`[ind_Cond6&rat_6],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond7&rat_6],
        Raw_data_withsoc$`Rel. Food`[ind_Cond7&rat_6],
        main = "Rat 6: Relative preference across 6 choice conditions",
        at = c(1,2, 4,5, 7,8, 10,11, 13,14, 16,17),
        names = c("Rel. Soc", "Rel. Food", "Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food")
        )

# Rat 8
boxplot(Raw_data_withsoc$`Rel. Soc`[ind_Cond1&rat_8], 
        Raw_data_withsoc$`Rel. Food`[ind_Cond1&rat_8], 
        Raw_data_withsoc$`Rel. Soc`[ind_Cond2&rat_8],
        Raw_data_withsoc$`Rel. Food`[ind_Cond2&rat_8], 
        Raw_data_withsoc$`Rel. Soc`[ind_Cond3&rat_8],
        Raw_data_withsoc$`Rel. Food`[ind_Cond3&rat_8],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond4&rat_8],
        Raw_data_withsoc$`Rel. Food`[ind_Cond4&rat_8],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond6&rat_8],
        Raw_data_withsoc$`Rel. Food`[ind_Cond6&rat_8],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond7&rat_8],
        Raw_data_withsoc$`Rel. Food`[ind_Cond7&rat_8],
        main = "Rat 8: Relative preference across 6 choice conditions",
        at = c(1,2, 4,5, 7,8, 10,11, 13,14, 16,17),
        names = c("Rel. Soc", "Rel. Food", "Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food")
        )

# All rats
boxplot(Raw_data_withsoc$`Rel. Soc`[ind_Cond1], 
        Raw_data_withsoc$`Rel. Food`[ind_Cond1], 
        Raw_data_withsoc$`Rel. Soc`[ind_Cond2],
        Raw_data_withsoc$`Rel. Food`[ind_Cond2], 
        Raw_data_withsoc$`Rel. Soc`[ind_Cond3],
        Raw_data_withsoc$`Rel. Food`[ind_Cond3],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond4],
        Raw_data_withsoc$`Rel. Food`[ind_Cond4],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond6],
        Raw_data_withsoc$`Rel. Food`[ind_Cond6],
        Raw_data_withsoc$`Rel. Soc`[ind_Cond7],
        Raw_data_withsoc$`Rel. Food`[ind_Cond7],
        main = "All Rats: Relative preference across 6 choice conditions",
        at = c(1,2, 4,5, 7,8, 10,11, 13,14, 16,17),
        names = c("Rel. Soc", "Rel. Food", "Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food","Rel. Soc", "Rel. Food")
        )

```

Fig 2. Food produced and shared (and left?) across conditions
```{r}

# Rat 4
boxplot(Raw_data_withsoc$`Sharing`[ind_Cond1&rat_4], 
        Raw_data_withsoc$`Total pellets`[ind_Cond1&rat_4], 
        Raw_data_withsoc$`Sharing`[ind_Cond2&rat_4],
        Raw_data_withsoc$`Total pellets`[ind_Cond2&rat_4], 
        Raw_data_withsoc$`Sharing`[ind_Cond3&rat_4],
        Raw_data_withsoc$`Total pellets`[ind_Cond3&rat_4],
        Raw_data_withsoc$`Sharing`[ind_Cond4&rat_4],
        Raw_data_withsoc$`Total pellets`[ind_Cond4&rat_4],
        Raw_data_withsoc$`Sharing`[ind_Cond6&rat_4],
        Raw_data_withsoc$`Total pellets`[ind_Cond6&rat_4],
        Raw_data_withsoc$`Sharing`[ind_Cond7&rat_4],
        Raw_data_withsoc$`Total pellets`[ind_Cond7&rat_4],
        main = "Rat 4: Food produced and shared across conditions",
        at = c(1,2, 4,5, 7,8, 10,11, 13,14, 16,17),
        names = c("Sharing", "Total pellets", "Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets")
        )

# Rat 6
boxplot(Raw_data_withsoc$`Sharing`[ind_Cond1&rat_6], 
        Raw_data_withsoc$`Total pellets`[ind_Cond1&rat_6], 
        Raw_data_withsoc$`Sharing`[ind_Cond2&rat_6],
        Raw_data_withsoc$`Total pellets`[ind_Cond2&rat_6], 
        Raw_data_withsoc$`Sharing`[ind_Cond3&rat_6],
        Raw_data_withsoc$`Total pellets`[ind_Cond3&rat_6],
        Raw_data_withsoc$`Sharing`[ind_Cond4&rat_6],
        Raw_data_withsoc$`Total pellets`[ind_Cond4&rat_6],
        Raw_data_withsoc$`Sharing`[ind_Cond6&rat_6],
        Raw_data_withsoc$`Total pellets`[ind_Cond6&rat_6],
        Raw_data_withsoc$`Sharing`[ind_Cond7&rat_6],
        Raw_data_withsoc$`Total pellets`[ind_Cond7&rat_6],
        main = "Rat 6: Food produced and shared across conditions",
        at = c(1,2, 4,5, 7,8, 10,11, 13,14, 16,17),
        names = c("Sharing", "Total pellets", "Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets")
        )

# Rat 8
boxplot(Raw_data_withsoc$`Sharing`[ind_Cond1&rat_8], 
        Raw_data_withsoc$`Total pellets`[ind_Cond1&rat_8], 
        Raw_data_withsoc$`Sharing`[ind_Cond2&rat_8],
        Raw_data_withsoc$`Total pellets`[ind_Cond2&rat_8], 
        Raw_data_withsoc$`Sharing`[ind_Cond3&rat_8],
        Raw_data_withsoc$`Total pellets`[ind_Cond3&rat_8],
        Raw_data_withsoc$`Sharing`[ind_Cond4&rat_8],
        Raw_data_withsoc$`Total pellets`[ind_Cond4&rat_8],
        Raw_data_withsoc$`Sharing`[ind_Cond6&rat_8],
        Raw_data_withsoc$`Total pellets`[ind_Cond6&rat_8],
        Raw_data_withsoc$`Sharing`[ind_Cond7&rat_8],
        Raw_data_withsoc$`Total pellets`[ind_Cond7&rat_8],
        main = "Rat 8: Relative preference across 6 choice conditions",
        at = c(1,2, 4,5, 7,8, 10,11, 13,14, 16,17),
        names = c("Sharing", "Total pellets", "Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets")
        )

# All rats
boxplot(Raw_data_withsoc$`Sharing`[ind_Cond1], 
        Raw_data_withsoc$`Total pellets`[ind_Cond1], 
        Raw_data_withsoc$`Sharing`[ind_Cond2],
        Raw_data_withsoc$`Total pellets`[ind_Cond2], 
        Raw_data_withsoc$`Sharing`[ind_Cond3],
        Raw_data_withsoc$`Total pellets`[ind_Cond3],
        Raw_data_withsoc$`Sharing`[ind_Cond4],
        Raw_data_withsoc$`Total pellets`[ind_Cond4],
        Raw_data_withsoc$`Sharing`[ind_Cond6],
        Raw_data_withsoc$`Total pellets`[ind_Cond6],
        Raw_data_withsoc$`Sharing`[ind_Cond7],
        Raw_data_withsoc$`Total pellets`[ind_Cond7],
        main = "All rats: Relative preference across 6 choice conditions",
        at = c(1,2, 4,5, 7,8, 10,11, 13,14, 16,17),
        names = c("Sharing", "Total pellets", "Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets","Sharing", "Total pellets")
        )

```

Relative food preference: Cond. 1 vs. 3
```{r}

mean_rel_food_c1    # The mean of food preference in the first condition
mean_rel_food_c3    # The mean of food preference in the Third condition

rel_food_c1 <- Raw_data$`Rel. Food`[ind_Cond1]
rel_food_c3 <- Raw_data$`Rel. Food`[ind_Cond3]

t_test_food_pref_13 <- t.test(rel_food_c1,rel_food_c3)
t_test_food_pref_13
# t = 8.6101, df = 38.763, p-value = 1.558e-10

```

Social response frequency range
```{r}

range(Raw_data$`Social `[ind_Cond1 | ind_Cond2 | ind_Cond3])
# 0.0000 0.6875
# Should we use the mean instead? 

# Mean of social response in cond. 1, 2, and 3
mean_soc_c1 <- mean(Raw_data$`Social ` [ind_Cond1])
mean_soc_c1
# 10.25926
mean_soc_c2 <- mean(Raw_data$`Social `[ind_Cond2])
mean_soc_c2
# 13.31818
mean_soc_c3 <- mean(Raw_data$`Social `[ind_Cond3])
mean_soc_c3
# 16.33333

```

Relative food response: cond. 3 vs. 4
```{r}

rel_food_c3 <- Raw_data$`Rel. Food`[ind_Cond3]
rel_food_c4 <- Raw_data$`Rel. Food`[ind_Cond4]

t_test_food_34 <- t.test(rel_food_c3,rel_food_c4)
t_test_food_34
# t = 3.0327, df = 42.643, p-value = 0.004114

```

***** Total pellets: cond. 4 vs. 7  (Is it comparison legistimate?) *****
```{r}

rel_soc_c4 <- Raw_data$`Rel. Soc`[ind_Cond4]
rel_soc_c7 <- Raw_data$`Rel. Soc`[ind_Cond7]

t_test_soc_47 <- t.test(rel_soc_c4,rel_soc_c7)
t_test
# t = 3.0327, df = 42.643, p-value = 0.004114

rel_food_c4 <- Raw_data$`Rel. Food`[ind_Cond4]
rel_food_c7 <- Raw_data$`Rel. Food`[ind_Cond7]

t_test_food_47 <- t.test(rel_food_c4,rel_food_c7)
t_test_food_47
# t = 3.0327, df = 42.643, p-value = 0.004114

```

Total pellets: cond. 3 vs. 4
```{r}

Tot_Pllt_3 <- Raw_data$`Total pellets`[ind_Cond3]
Tot_Pllt_4 <- Raw_data$`Total pellets`[ind_Cond4]

t_test_pellet_34 <- t.test(Tot_Pllt_3,Tot_Pllt_4)
t_test_pellet_34
# t = 5.6621, df = 37.265, p-value = 1.761e-06

```

Mean of sharing 
```{r}
Raw_data_sharing <- subset(Raw_data, `Sharing` !=-1)

mean_sharing <- mean(Raw_data_sharing$Sharing)
mean_sharing
# 1.092308
```

